# Generated by Django 4.2.3 on 2023-07-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("BC", "Cycle"),
                    ("SC", "Scooty"),
                    ("BK", "Bike"),
                    ("CO", "Cooler"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
